[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rpze"
version = "0.0.1"
dependencies = [
    "keystone-engine>=0.9.2", 
    "pywin32"
]
requires-python = ">=3.11"

[tool.setuptools.package-data]
"*" = ["*.pyd", "*.pyi", "rp_dll.dll", "rp_injector.exe"] 